# Generated by Django 5.2.12 on 2026-03-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(db_column='search_query_id', primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('query_topic', models.IntegerField(blank=True, null=True)),
                ('filters', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'db_table': 'search_queries',
                'ordering': ['-id'],
            },
        ),
    ]
