# Generated by Django 5.2.12 on 2026-03-23 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user'], name='idx_search_queries_user_id'),
        ),
    ]
